Update eas-build.yml

diff --git a/.github/workflows/eas-build.yml b/.github/workflows/eas-build.yml
--- a/.github/workflows/eas-build.yml
+++ b/.github/workflows/eas-build.yml
@@ -20,6 +20,18 @@ jobs:
         run: |
           current_version=$(node -p "require('./package.json').version")
           previous_version=$(git log -n 1 --pretty=format:%s | grep -oP "(?<=Bump version to )\d+\.\d+\.\d+")
+          echo "$previous_version"
+          if [[ "$current_version" == "$previous_version" || $(echo "$current_version <= $previous_version" | bc -l) -eq 1 ]]; then
+            echo "Version check failed. Stopping workflow."
+            exit 1
+          else
+            echo "Version check passed. Continuing workflow."
+          fi
+
+      - name: Check app.json expo version
+        run: |
+          current_version=$(node -p "require('./app.json').expo.version")
+          previous_version=$(git log -n 1 --pretty=format:%s | grep -oP "(?<=Bump version to )\d+\.\d+\.\d+")
           if [[ "$current_version" == "$previous_version" || $(echo "$current_version <= $previous_version" | bc -l) -eq 1 ]]; then
             echo "Version check failed. Stopping workflow."
             exit 1
